# -----------------------------------------------
# GitHub Actions Basics

# Copyright (c) by Dmitry Plastun 2025
#------------------------------------------------

name: My-GitHubActions-BASICS
env:
  APP_NAME     : "MyFlask"
  PACKAGE_NAME : "flask-deploy-ver-${{ github.sha }}"
on: 
  push: 
    branches: 
      - main

jobs:
  my_testing: 
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World from Test
      run: echo "Hello, World!"
    
    - name: Execute few commands
      run: |
        echo "Hello Message 1"
        echo "Hello Message 2"
        echo "Application name: ${{ env.APP_NAME }}"

    - name: Git clone my repository
      uses: actions/checkout@v1

    - name: List current folder
      run: ls -la

    - name: Test AWS packages
      run: aws --version
      
    - name: Start command ZIP
      run: |
        zip
        ip a
  
  my_deploy: 
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      LOCAL_DEPLOY_VAR1: "This is Job Level 1"
      LOCAL_DEPLOY_VAR2: "This is Job Level 2"
    
    steps:
    - name: Print Hello World from Deploy
      run: echo "Hello, World! from Deploy job"

    - name: Printing Deployment package
      run: echo "Deploy package name is ${{ env.PACKAGE_NAME}}"
    
    - name: Print env variables
      run: |
        echo "Var1 = ${{ env.LOCAL_DEPLOY_VAR1 }}"
        echo "Var2 = ${{ env.LOCAL_DEPLOY_VAR2 }}"
        echo "Var3 = $LOCAL_STEP_VAR"
      env:
        LOCAL_STEP_VAR: "Local Step Var"
