# -----------------------------------------------
# GitHub Actions Basics

# Copyright (c) by Dmitry Plastun 2025
#------------------------------------------------

name: My-GitHubActions-BASICS

on: 
  push: 
    branches: 
      - master

jobs:
  my_testing: 
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World from Test
      run: echo "Hello, World!"

  
  my_deploy: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello World from Deploy
      run: echo "Hello, World! from Deploy job"
